# Continuous Variable Quantum Information

- Author: Longfei Fan
- Created Date: 07/01/2016
- The Second Last Modified: 11/15/2016
- The Lasd Modified: 11/18/2016

This file shows some useful functions in Gausssian quantum information, inlcuding

1. Dispalcement Operator
2. Single-Mode Squeezing Operator
3. Two-Mode Squeezing Operator
4. Two-Mode Mixing (Beam Splitter) Operator

Examples are given with `QuTip`.

In [1]:
from qutip import *
import numpy as np
import math as mt

In [2]:
np.set_printoptions(threshold='nan', precision=6, suppress=True)

In [3]:
def comb(N, k):
    f = mt.factorial
    return f(N) / f(k) / f(N-k)

# I. Preparation

## 1. Displacement Operator

$$ D(\alpha) = \exp\left(\alpha \hat{a}^{\dagger} - \alpha^* \hat{a}\right) $$

Acting on the vacuum state gives the coherent state
$$ D(\alpha) \left|0 \right\rangle = \left| \alpha \right\rangle $$

The normal ordering is
$$ D(\alpha) = \exp(\alpha \hat{a}^{\dagger}) \exp(-\alpha^* \hat{a}) \exp(-|\alpha|^2/2) $$

The mode evolution is
$$ D(\alpha)^{\dagger} a D(\alpha) = a + \alpha $$
$$ D(\alpha)^{\dagger} a^\dagger D(\alpha) = a^* + \alpha$$

In [6]:
d = displace(5, 0.1)
d

Quantum object: dims = [[5], [5]], shape = [5, 5], type = oper, isherm = False
Qobj data =
[[ 0.995012 -0.099501  0.007036 -0.000406  0.00002 ]
 [ 0.099501  0.985062 -0.140012  0.012146 -0.000812]
 [ 0.007036  0.140012  0.975162 -0.170618  0.017191]
 [ 0.000406  0.012146  0.170618  0.965229 -0.197676]
 [ 0.00002   0.000812  0.017191  0.197676  0.980116]]

In [7]:
d * basis(5, 0)

Quantum object: dims = [[5], [1]], shape = [5, 1], type = ket
Qobj data =
[[ 0.995012]
 [ 0.099501]
 [ 0.007036]
 [ 0.000406]
 [ 0.00002 ]]

In [8]:
coherent(5, 0.1)

Quantum object: dims = [[5], [1]], shape = [5, 1], type = ket
Qobj data =
[[ 0.995012]
 [ 0.099501]
 [ 0.007036]
 [ 0.000406]
 [ 0.00002 ]]

## 2. Single-mode Squeezing Operator

### $$ S(\xi) = \exp \left(\frac{\xi^*}{2} \hat{a}^2 - \frac{\xi}{2} \hat{a}^{\dagger 2} \right) $$

In [9]:
S1 = squeeze(5, 0.1)

In [10]:
S1

Quantum object: dims = [[5], [5]], shape = [5, 5], type = oper, isherm = False
Qobj data =
[[ 0.997507  0.        0.070299  0.        0.006106]
 [ 0.        0.992509  0.        0.122169  0.      ]
 [-0.070299  0.        0.982551  0.        0.172196]
 [ 0.       -0.122169  0.        0.992509  0.      ]
 [ 0.006106  0.       -0.172196  0.        0.985044]]

In [11]:
smsv = S1 * basis(5, 0)

In [12]:
smsv

Quantum object: dims = [[5], [1]], shape = [5, 1], type = ket
Qobj data =
[[ 0.997507]
 [ 0.      ]
 [-0.070299]
 [ 0.      ]
 [ 0.006106]]

In [13]:
S11 = (0.05 * (- create(5) ** 2 + destroy(5) ** 2)).expm()

In [14]:
S11

Quantum object: dims = [[5], [5]], shape = [5, 5], type = oper, isherm = False
Qobj data =
[[ 0.997507  0.        0.070299  0.        0.006106]
 [ 0.        0.992509  0.        0.122169  0.      ]
 [-0.070299  0.        0.982551  0.        0.172196]
 [ 0.       -0.122169  0.        0.992509  0.      ]
 [ 0.006106  0.       -0.172196  0.        0.985044]]

In [15]:
S11 * basis(5, 0)

Quantum object: dims = [[5], [1]], shape = [5, 1], type = ket
Qobj data =
[[ 0.997507]
 [ 0.      ]
 [-0.070299]
 [ 0.      ]
 [ 0.006106]]

In [17]:
s = 0.1
[(- np.tanh(s))**k * np.sqrt(mt.factorial(2*k)) \
 / (2**k * mt.factorial(k)) for k in xrange(5)] / np.sqrt(np.cosh(s))

array([ 0.997507, -0.0703  ,  0.006068, -0.000552,  0.000051])

## 3. Two-mode Squeezing Operator

$$ S_2(\xi) = \exp \left(-\xi^*\hat{a}\hat{b} + \xi\hat{a}^{\dagger}\hat{b}^{\dagger}\right) $$

In [18]:
def two_mode_squeezing(N, s):
    """ Two-mode squeezing operator. 
    Photon number is truncated to N"""
    a = destroy(N)
    b = destroy(N)
    return (- np.conj(s) * tensor(a, b) + 
            s * tensor(a.dag(), b.dag())).expm()

In [19]:
S2 = two_mode_squeezing(5, 0.1)
vaccum = tensor(basis(5, 0), basis(5, 0))

In [20]:
tmsv = S2 * vaccum
tmsv.trans().full()

array([[ 0.995021+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.099172+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.009884+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000985+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000099+0.j]])

In [21]:
tmsv.norm()

1.0

In [22]:
def tmss(N, s):
    """ Two-mode squeezing vaccum"""
    v = np.sinh(s)
    u = np.cosh(s)
    tmsv = [(v/u) ** k * tensor(basis(N, k), basis(N, k)) 
            for k in xrange(N)]
    return np.sum(tmsv) / u

In [23]:
state = tmss(5, 0.1)

In [24]:
tmsv.overlap(state)

(0.99999999995130029+0j)

## 4. Two-mode Mixing (Beam-splitter Operator)

$$ U(\xi) = \exp \left(\xi\hat{a}^{\dagger}\hat{b} - \xi^*\hat{a}\hat{b}^{\dagger}\right) $$
<img src='BS.png', width=300>
**IMPORTANT:** By convention, if subscripts are omitted, the input state is in the oder of $\left|n\right\rangle_0\left|m\right\rangle_1 $, and the output state is in the order of $\left|k\right\rangle_2\left|l\right\rangle_3$. 0, 1, 2, and 3 are shown in the above picture.

In [5]:
def two_mode_mixing(N, s):
    """ Two-mode mixing operator. 
    Photon number is truncated at N. """
    a = destroy(N)
    b = destroy(N)
    return (s * tensor(a.dag(), b) - 
            np.conj(s) * tensor(a, b.dag())).expm()

### 4.1 $U(\frac{\pi}{4})$ act on $\left| 01 \right\rangle$ and $\left| 10 \right\rangle$

$$
U \left(\frac{\pi}{4} \right) \left| 01 \right\rangle = \exp \left[\frac{\pi}{4} \left(\hat{a}^{\dagger}\hat{b} - \hat{a}\hat{b}^{\dagger} \right)\right] \left| 01 \right\rangle = \frac{\left| 01 \right\rangle  + \left| 10 \right\rangle}{\sqrt{2}}
$$

$$
U \left(\frac{\pi}{4} \right) \left| 10 \right\rangle = \exp \left[\frac{\pi}{4} \left(\hat{a}^{\dagger}\hat{b} - \hat{a}\hat{b}^{\dagger} \right)\right] \left| 10 \right\rangle = \frac{- \left| 01 \right\rangle  + \left| 10 \right\rangle}{\sqrt{2}}
$$

In [6]:
op = two_mode_mixing(2, np.pi / 4)

**In state vector form**

In [10]:
ins = tensor(basis(2, 0), basis(2, 1))
ins.trans()

Quantum object: dims = [[1, 1], [2, 2]], shape = [1, 4], type = bra
Qobj data =
[[ 0.  1.  0.  0.]]

In [11]:
ket2dm(ins)

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

In [12]:
ins = tensor(basis(2, 0), basis(2, 1))
outs =  op * ins
outs.trans()

Quantum object: dims = [[1, 1], [2, 2]], shape = [1, 4], type = bra
Qobj data =
[[ 0.        0.707107  0.707107  0.      ]]

In [13]:
ket2dm(outs)

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 0.   0.   0.   0. ]
 [ 0.   0.5  0.5  0. ]
 [ 0.   0.5  0.5  0. ]
 [ 0.   0.   0.   0. ]]

In [15]:
ins = tensor(basis(2, 1), basis(2, 0))
outs = op * ins
outs.trans()

Quantum object: dims = [[1, 1], [2, 2]], shape = [1, 4], type = bra
Qobj data =
[[ 0.       -0.707107  0.707107  0.      ]]

In [16]:
ket2dm(outs)

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 0.   0.   0.   0. ]
 [ 0.   0.5 -0.5  0. ]
 [ 0.  -0.5  0.5  0. ]
 [ 0.   0.   0.   0. ]]

### 4.2 $U(i\frac{\pi}{4})$ Act on $\left| 01 \right\rangle$ and $\left| 10 \right\rangle$

$$
U \left(i\frac{\pi}{4} \right) \left| 01 \right\rangle = \exp \left[i\frac{\pi}{4} \left(\hat{a}^{\dagger}\hat{b} + \hat{a}\hat{b}^{\dagger} \right)\right] \left| 01 \right\rangle = \frac{\left| 01 \right\rangle  + i \left| 10 \right\rangle}{\sqrt{2}}
$$
$$
U \left(i\frac{\pi}{4} \right) \left| 10 \right\rangle = \exp \left[i\frac{\pi}{4} \left(\hat{a}^{\dagger}\hat{b} + \hat{a}\hat{b}^{\dagger} \right)\right] \left| 10 \right\rangle = \frac{\left| 10 \right\rangle  + i \left| 01 \right\rangle}{\sqrt{2}}
$$
Pay attention to the order! With all subscripts, the above evolution is acutally given as

$$
\left|0\right\rangle_0\left|1\right\rangle_1 \to \frac{\left|0\right\rangle_2\left|1\right\rangle_3  + i~ \left|1\right\rangle_2\left|0\right\rangle_3}{\sqrt{2}}
$$
$$
\left|1\right\rangle_0\left|0\right\rangle_1 \to \frac{i~ \left|0\right\rangle_2\left|1\right\rangle_3 + \left|1\right\rangle_2\left|0\right\rangle_3}{\sqrt{2}}
$$

In [17]:
op = two_mode_mixing(2, 1j * np.pi / 4)

In [20]:
ins = tensor(basis(2, 0), basis(2, 1))
ins

Quantum object: dims = [[2, 2], [1, 1]], shape = [4, 1], type = ket
Qobj data =
[[ 0.]
 [ 1.]
 [ 0.]
 [ 0.]]

In [18]:
outs = op * ins
outs

Quantum object: dims = [[2, 2], [1, 1]], shape = [4, 1], type = ket
Qobj data =
[[ 0.000000+0.j      ]
 [ 0.707107+0.j      ]
 [ 0.000000+0.707107j]
 [ 0.000000+0.j      ]]

In [21]:
ket2dm(outs)

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 0.0+0.j   0.0+0.j   0.0+0.j   0.0+0.j ]
 [ 0.0+0.j   0.5+0.j   0.0-0.5j  0.0+0.j ]
 [ 0.0+0.j   0.0+0.5j  0.5+0.j   0.0+0.j ]
 [ 0.0+0.j   0.0+0.j   0.0+0.j   0.0+0.j ]]

In [22]:
ins = tensor(basis(2, 1), basis(2, 0))
ins

Quantum object: dims = [[2, 2], [1, 1]], shape = [4, 1], type = ket
Qobj data =
[[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]]

In [23]:
outs = two_mode_mixing(2, 1j * np.pi / 4) * ins
outs

Quantum object: dims = [[2, 2], [1, 1]], shape = [4, 1], type = ket
Qobj data =
[[ 0.000000+0.j      ]
 [ 0.000000+0.707107j]
 [ 0.707107+0.j      ]
 [ 0.000000+0.j      ]]

In [24]:
ket2dm(outs)

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 0.0+0.j   0.0+0.j   0.0+0.j   0.0+0.j ]
 [ 0.0+0.j   0.5+0.j   0.0+0.5j  0.0+0.j ]
 [ 0.0+0.j   0.0-0.5j  0.5+0.j   0.0+0.j ]
 [ 0.0+0.j   0.0+0.j   0.0+0.j   0.0+0.j ]]

### 4.3 Act on $\left| 11 \right\rangle$

$$
U \left(i\frac{\pi}{4} \right) \left| 11 \right\rangle = \exp \left[i\frac{\pi}{4} \left(\hat{a}^{\dagger}\hat{b} + \hat{a}\hat{b}^{\dagger} \right)\right] \left| 11 \right\rangle = \frac{i}{2} \left( \left| 02 \right\rangle  + \left| 20 \right\rangle \right)
$$

In [29]:
ins = tensor(basis(3, 1), basis(3, 1))
outs = two_mode_mixing(3, 1j * np.pi / 4) * insp
outs.trans()

Quantum object: dims = [[1, 1], [3, 3]], shape = [1, 9], type = bra
Qobj data =
[[ 0.+0.j        0.+0.j        0.+0.707107j  0.+0.j        0.+0.j        0.+0.j
   0.+0.707107j  0.+0.j        0.+0.j      ]]

### 4.4 Act on $\left| 0 \right\rangle \left| \alpha \right\rangle$

$$
U \left(i\frac{\pi}{4} \right) \left| 0 \right\rangle \left| \alpha \right\rangle = \exp \left[i\frac{\pi}{4} \left(\hat{a}^{\dagger}\hat{b} + \hat{a}\hat{b}^{\dagger} \right)\right] \left| 0 \right\rangle \left| \alpha \right\rangle = \left| \frac{i\alpha}{\sqrt{2}} \right\rangle \left| \frac{\alpha^*}{\sqrt{2}} \right\rangle
$$

In [30]:
ins = tensor(basis(5, 0), coherent(5, 0.5))
outs = two_mode_mixing(5, 1j * np.pi / 4) * ins
outs.trans().full()

array([[ 0.882497+0.j      ,  0.312009+0.j      ,  0.078006+0.j      ,
         0.015898+0.j      ,  0.002934+0.j      ,  0.000000+0.312009j,
         0.000000+0.110317j,  0.000000+0.027536j,  0.000000+0.005867j,
         0.000000+0.j      , -0.078006+0.j      , -0.027536+0.j      ,
        -0.007186+0.j      ,  0.000000+0.j      ,  0.000000+0.j      ,
         0.000000-0.015898j,  0.000000-0.005867j,  0.000000+0.j      ,
         0.000000+0.j      ,  0.000000+0.j      ,  0.002934+0.j      ,
         0.000000+0.j      ,  0.000000+0.j      ,  0.000000+0.j      ,
         0.000000+0.j      ]])

In [31]:
outs2 = tensor(coherent(5, 0.5j/np.sqrt(2)), 
               coherent(5, 0.5/np.sqrt(2)))
outs2.trans().full()

array([[ 0.882497+0.j      ,  0.312010+0.j      ,  0.078003+0.j      ,
         0.015916+0.j      ,  0.002874+0.j      ,  0.000000+0.31201j ,
         0.000000+0.110312j,  0.000000+0.027578j,  0.000000+0.005627j,
         0.000000+0.001016j, -0.078003+0.j      , -0.027578+0.j      ,
        -0.006895+0.j      , -0.001407+0.j      , -0.000254+0.j      ,
         0.000000-0.015916j,  0.000000-0.005627j,  0.000000-0.001407j,
         0.000000-0.000287j,  0.000000-0.000052j,  0.002874+0.j      ,
         0.001016+0.j      ,  0.000254+0.j      ,  0.000052+0.j      ,
         0.000009+0.j      ]])

In [32]:
outs.tr(), outs.norm(), outs2.tr(), outs2.norm()

((0.8824969330377003+0j), 1.0, (0.8824969044258281+0j), 1.0000000000000002)

In [33]:
outs.overlap(outs2)

(0.99999677457459235+0j)

### 4.5 Act on $\left| \alpha \right\rangle \left| \beta \right\rangle$

$$
U \left(i\frac{\pi}{4} \right) \left| \alpha \right\rangle \left| \beta \right\rangle
= \exp \left[i\frac{\pi}{4} \left(\hat{a}^{\dagger}\hat{b} + \hat{a}\hat{b}^{\dagger} \right)\right] \left| \alpha \right\rangle \left| \beta \right\rangle 
= \left| \frac{\alpha + i\beta}{\sqrt{2}} \right\rangle \left| \frac{i\alpha + \beta}{\sqrt{2}} \right\rangle
$$

In [34]:
ins = tensor(coherent(5, 0.5), coherent(5, 1))
outs = two_mode_mixing(5, 1j * np.pi / 4) * ins
outs.trans().full()

array([[ 0.535285+0.j      ,  0.378331+0.189251j,  0.142593+0.189165j,
         0.017285+0.106651j, -0.007233+0.039549j,  0.189251+0.378331j,
         0.000000+0.335484j, -0.083844+0.163706j, -0.066811+0.060652j,
        -0.012857+0.00139j , -0.142593+0.189165j, -0.163706+0.083844j,
        -0.116574+0.j      , -0.024612+0.000297j, -0.001733-0.004973j,
        -0.106651-0.017285j, -0.066811-0.060652j, -0.041666-0.022765j,
        -0.008247-0.012733j, -0.006543+0.j      , -0.007233-0.039549j,
        -0.018408-0.050953j, -0.019386-0.004973j, -0.002828+0.j      ,
         0.001708+0.j      ]])

In [35]:
outs2 = tensor(coherent(5, (0.5 + 1j)/np.sqrt(2)), 
               coherent(5, (0.5j + 1)/np.sqrt(2)))
outs2.trans().full()

array([[ 0.535265+0.j      ,  0.378467+0.189233j,  0.142048+0.189397j,
         0.019122+0.105173j, -0.013236+0.045382j,  0.189233+0.378467j,
         0.000000+0.3345j  , -0.083697+0.167394j, -0.067603+0.050702j,
        -0.036767+0.006685j, -0.142048+0.189397j, -0.167394+0.083697j,
        -0.104712+0.j      , -0.042289-0.021144j, -0.012545-0.016727j,
        -0.105173-0.019122j, -0.067603-0.050702j, -0.021144-0.042289j,
         0.000000-0.021348j,  0.004222-0.008444j, -0.013236-0.045382j,
         0.006685-0.036767j,  0.012545-0.016727j,  0.008444-0.004222j,
         0.004175+0.j      ]])

In [36]:
outs.tr(), outs.norm(), outs2.tr(), outs2.norm()

((0.5352845312562375+0j),
 0.9999999999999999,
 (0.535265413786181+0j),
 0.9999999999999996)

In [37]:
outs.overlap(outs2)

(0.99729075785497656+0.0033926854404569633j)

### 4.6 Act on $\left| 0 \right\rangle \left| N \right\rangle$

$$
U \left(i\frac{\pi}{4} \right) \left| 0 \right\rangle \left| N \right\rangle
= \exp \left[i\frac{\pi}{4} \left(\hat{a}^{\dagger}\hat{b} + \hat{a}\hat{b}^{\dagger} \right)\right] \left| 0 \right\rangle \left| N \right\rangle 
= 2^{-\frac{N}{2}} \sum_{k=0}^{N} i^k \binom{N}{k} \left| k \right\rangle \left| N - k \right\rangle
$$

In [38]:
ins = tensor(basis(5, 0), basis(5, 4))
outs = two_mode_mixing(5, 1j * np.pi / 4) * ins
outs.trans().full()

array([[ 0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.250000+0.j ,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.000000+0.5j,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
        -0.612372+0.j ,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.000000-0.5j,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.250000+0.j ,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.000000+0.j ]])

In [39]:
outs2 = 2**(-2) * np.sum([1j**k * np.sqrt(comb(4, k)) * 
                          tensor(basis(5, k), basis(5, 4 - k)) 
                          for k in xrange(5)])

In [40]:
outs2.trans().full()

array([[ 0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.250000+0.j ,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.000000+0.5j,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
        -0.612372+0.j ,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.000000-0.5j,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.250000+0.j ,  0.000000+0.j ,  0.000000+0.j ,  0.000000+0.j ,
         0.000000+0.j ]])

### 4.7 Act on $\left| n \right\rangle \left| m \right\rangle$

$$
\begin{aligned}
U \left(\theta \right) \left| n \right\rangle_0 \left| m \right\rangle_1
=~& \exp \left[\theta \left(\hat{a}^{\dagger}\hat{b} - \hat{a}\hat{b}^{\dagger} \right)\right] \left| n \right\rangle_0 \left| m \right\rangle_1 \\
=~& \sum_{k=0}^{n} \sum_{l=0}^{m} (-1)^k \kappa^\frac{n+m-k-l}{2} (1-\kappa)^\frac{k+l}{2} \left[\binom{n}{k} \binom{m}{l} \binom{n-k+l}{l} \binom{m+k-l}{k}\right]^\frac{1}{2} \left| n-k+l \right\rangle_2 \left| m+k-l \right\rangle_3
\end{aligned}
$$

Derivation is given as follows. The input states is

$$
\left| in \right\rangle = \left| n \right\rangle_0 \left| m \right\rangle_1 = \frac{a_0^{\dagger n}}{\sqrt{n!}} \frac{a_1^{\dagger m}}{\sqrt{m!}} \left| 0 \right\rangle_0 \left| 0 \right\rangle_1
$$

And we have

$$
a_0 = \cos\theta~a_2^\dagger - \sin\theta~a_3^\dagger,~~~~ a_1 = \sin\theta~a_2^\dagger + \cos\theta~a_3^\dagger,
$$

$$
\sin\theta = \sqrt{1-\kappa},~~~~ \cos{\theta} = \sqrt{\kappa}
$$

After the beam spliiter, we obtain

$$
\begin{aligned}
\left| out \right\rangle=~& \frac{1}{\sqrt{n!m!}} \left(\cos\theta~a_2^\dagger - \sin\theta~a_3^\dagger\right)^n \left(\sin\theta~a_2^\dagger + \cos\theta~a_3^\dagger\right)^m \left| 0 \right\rangle_2 \left| 0 \right\rangle_3 \\
=~& \frac{1}{\sqrt{n!m!}} \sum_{k=0}^{n} \sum_{l=0}^{m} \binom{n}{k} \binom{m}{l} \left(\cos\theta~a_2^\dagger\right)^{n-k} \left(-\sin\theta~a_3^\dagger\right)^k \left(\sin\theta~a_2^\dagger\right)^{l} \left(\cos\theta~a_3^\dagger\right)^{m-l} \left| 0 \right\rangle_2 \left| 0 \right\rangle_3 \\
=~& \sum_{k=0}^{n} \sum_{l=0}^{m} (-1)^k \left(\cos\theta\right)^{n+m-k-l} \left(\sin\theta\right)^{k+l} \left[\frac{n!m!(n-k+l)!(m+k-l)!}{(n-k)!k!(n-k)!k!(m-l)!l!(m-l)!l!}\right]^\frac{1}{2} \left| n-k+l \right\rangle_2 \left| m+k-l \right\rangle_3 \\
=~& \sum_{k=0}^{n} \sum_{l=0}^{m} (-1)^k \kappa^\frac{n+m-k-l}{2} (1-\kappa)^\frac{k+l}{2} \left[\binom{n}{k} \binom{m}{l} \binom{n-k+l}{l} \binom{m+k-l}{k}\right]^\frac{1}{2} \left| n-k+l \right\rangle_2 \left| m+k-l \right\rangle_3
\end{aligned}
$$

In [41]:
n = 3
m = 6
N = n + m + 1
theta = np.pi / 4
ins = tensor(basis(N, n), basis(N, m))
outs = two_mode_mixing(N, theta) * ins
outs.trans().full()

array([[ 0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j, -0.405046+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j, -0.405046+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.353553+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.216506+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j, -0.216506+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+

In [42]:
def ker(k, l):
    para = (-1)**k * np.cos(theta)**(n+m-k-l) * np.sin(theta)**(k+l) 
    para *= np.sqrt(comb(n, k) * comb(m, l) * comb(n - k + l, l) * comb(m + k -l, k))
    return para * tensor(basis(N, n - k + l), basis(N, m + k -l))
outs2 = np.sum([[ker(k, l) for k in xrange(4)] for l in xrange(7)])

In [43]:
outs2.trans().full()

array([[ 0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j, -0.405046+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j, -0.405046+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.353553+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.216506+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j, -0.216506+0.j,  0.000000+0.j,
         0.000000+0.j,  0.000000+0.j,  0.000000+

In [44]:
outs.overlap(outs2)

(1+0j)